apiVersion: harness.io/v1
kind: Workflow
idnetifier: rbacmanageraccount
name: Manage Harness Account Group Membership
owner: group:default/harness_account_all_users # Defaults to all users
type: harness_factory
metadata:
  description: Manage Harness Organization UserGroup membership
  tags:
    - solutions-factory
    - harness
    - hidden
    - account-management
spec:
  parameters:
    - title: Choose Target Details
      description: ""
      required:
        - harness_group_action
      properties:
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        harness_group_action:
          title: What action should be applied
          type: string
          description: What action should be applied
          enum:
            - add
            - remove
            - purge
          enumNames:
            - Add users to chosen Harness Groups
            - Remove users from chosen Harness Groups
            - Remove users from accessing scope
      dependencies:
        harness_group_action:
          allOf:
            - if:
                properties:
                  harness_group_action:
                    const: purge
              then:
                required:
                  - approve_purge
                properties:
                  approve_purge:
                    title: Removing a user from a Project will remove all permissions and group
                      memberships for that user within the project. Resources created by the user(s) will not be removed.
                    type: string
                    default: no
                    pattern: yes
                    enum:
                      - no
                      - yes
                    enumNames:
                      - "No: Do not continue this disruptive change"
                      - "Yes: I understand the risks"

    - title: Manage Memberships
      description: ""
      properties:
        email_addresses:
          title: Add Email Addresses to manage
          type: array
          description: Add Email Addresses to manage
          ui:options:
            addable: true
            orderable: true
            removable: true
          items:
            type: string
        harness_groups:
          title: Add Harness Groups to manage
          type: array
          description: Add Harness Groups to manage
          ui:options:
            addable: true
            orderable: true
            removable: true
          items:
            type: string
    - title: Solutions Factory Connection
      properties:
        solutions_factory_details:
          title: Solutions Factory Details
          type: object
          description: |
            ---
            Harness URL : <+variable.account.solutions_factory_endpoint>

            Harness Account : <+account.identifier>

            Solutions Factory Org : <+variable.account.solutions_factory_org>

            Solutions Factory Project : <+variable.account.solutions_factory_project>
          properties:
            harness_account_url:
              type: string
              default: <+variable.account.solutions_factory_endpoint>
              ui:widget: hidden
            harness_account_id:
              type: string
              default: <+account.identifier>
              ui:widget: hidden
            harness_org_id:
              type: string
              default: <+variable.account.solutions_factory_org>
              ui:widget: hidden
            harness_project_id:
              type: string
              default: <+variable.account.solutions_factory_project>
              ui:widget: hidden
            harness_pipeline_id:
              type: string
              default: RBAC_Management
              ui:widget: hidden
            template_library_connector:
              type: string
              default: <+variable.account.solutions_factory_template_library_connector>
              ui:widget: hidden
  steps:
    - id: rbac-manager
      name: Modify UserGroup Membership
      action: trigger:harness-custom-pipeline
      input:
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ parameters.solutions_factory_details.harness_project_id }}/pipelines/${{ parameters.solutions_factory_details.harness_pipeline_id }}/pipeline-studio?storeType=INLINE
        inputset:
          email_addresses: ${{ parameters.email_addresses.join(",") }}
          group_id: ${{ parameters.harness_groups.join(",") }}
          group_action: ${{ parameters.harness_group_action }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    text:
      - title: Outputs
        content: |
          {% if parameters.harness_group_action != "purge" %}
          User Groups Updated
          ---
          {% for email_address in parameters.email_addresses %}
          Email: ${{ email_address }}

          -> Action Taken: ${{ parameters.harness_group_action | title }}

          {% for user_group in parameters.harness_groups %}
          -> Group: ${{ user_group }}
          {% endfor %}

          {% endfor %}
          {% else %}
          Users Updated
          ---
          {% for email_address in parameters.email_addresses %}
          Email: ${{ email_address }}

          -> Action Taken: ${{ parameters.harness_group_action | title }}
          {% endfor %}
          {% endif %}
