inputSet:
  identifier: ${INPUTSET_IDENTIFIER}
  name: ${INPUTSET_NAME}
  orgIdentifier: ${ORGANIZATION_ID}
  projectIdentifier: ${PROJECT_ID}
  pipelineIdentifier:
  description: "${DESCRIPTION}"
  tags:
    ${indent(4, TAGS)}
  pipeline:
    identifier: ${PIPELINE_IDENTIFIER}
    properties:
      ci:
        codebase:
          build: <+input>
    stages:
      - stage:
          identifier: Build
          template:
            templateInputs:
              type: CI
              spec:
                execution:
                  steps:
                    - insert:
                        identifier: Install_Dependency
                        steps: ""
                    - parallel:
                        - insert:
                            identifier: Extra_Code_Scanning_Block
                            steps: ""
                    - insert:
                        identifier: Test_Block
                        steps: ""
                    - stepGroup:
                        identifier: Build_and_Scan
                        template:
                          templateInputs:
                            steps:
                              - step:
                                  identifier: Build_and_Push_Docker
                                  type: BuildAndPushDockerRegistry
                                  spec:
                                    connectorRef: <+input>
                              - step:
                                  identifier: Push_to_Docker
                                  type: BuildAndPushDockerRegistry
                                  spec:
                                    connectorRef: <+input>
                    - stepGroup:
                        identifier: SCS
                        template:
                          templateInputs:
                            steps:
                              - step:
                                  identifier: ArtifactSigning
                                  type: SscaArtifactSigning
                                  spec:
                                    signing:
                                      type: cosign
                                      spec:
                                        private_key: <+input>
                                        password: <+input>
              variables:
                - name: DOCKER_REPOSITORY
                  type: String
                  value: <+input>
                - name: DOCKER_TAG
                  type: String
                  value: <+input>
