apiVersion: harness.io/v1
kind: Workflow
identifier: ccmautostopprimer
name: AutoStopping Step Template Setup
owner: group:default/harness_account_all_users
type: Pipeline
metadata:
  description: Create a step template for creating autostopping rules. Also provide a workflow for users to add required variables to their services.
  tags:
    - solutions-factory
    - harness
    - ccm
    - autostopping
    - cd
spec:
  parameters:
    - title: Template Location
      description: Where should the Kubernetes manifests and Step Template be located
      required:
        - template_name
        - template_version
        - template_location
      properties:
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        template_name:
          title: Step Template Name
          type: string
          description: What should the "Create AutoStopping Rule" step template be named
          default: Auto-Stop Ingress
        template_version:
          title: Step Template Version
          type: string
          description: What should the step template's initial version be
          default: "1.0"
        template_location:
          title: Template Location
          type: string
          description: Where should we place the template?
          enum:
            - Account
            - Organization
            - Project
      dependencies:
        template_location:
          oneOf:
          - properties:
              template_location:
                enum:
                  - Account
          - properties:
              template_location:
                enum:
                  - Organization
              org_id:
                title: Org Identifier
                description: Harness Organization Identifier
                type: string
                ui:field: HarnessOrgPicker
            required:
              - org_id
          - properties:
              template_location:
                enum:
                  - Project
              project_id:
                title: Project Identifier
                description: Harness Project Identifier
                type: string
                ui:field: HarnessProjectPicker
              org_id:
                title: Org Identifier
                description: Harness Organization Identifier
                type: string
                ui:field: HarnessOrgPicker
                # ui:field: HarnessAutoOrgPicker
                # dependencies:
                #   projectPickerRef:
                #     - 'project_id'
            required:
              - project_id
              - org_id
    - title: Pipeline Setup
      required:
        - build_infrastructure_type
        - harness_endpoint
        - harness_platform_api_key_secret
        - docker_connector
        - image
      properties:
        existing_harness_platform_key_ref:
          type: string
          description: Existing secret ID for Harness API key that can modify CD services
          default: org.hsf_platform_api_key
        docker_connector:
          title: Docker Connector
          type: string
          description: Docker connector ID for pulling plugin image
          default: account.harnessImage
        image:
          title: Plugin Image for Modifying Services
          type: string
          default: harnesscommunity/add-autostopping-variables:576e4f594a80d482f77761f4ca8b715cf25c983d
          description: Plugin docker image to use for modifying services. Must follow repo/image:tag format
        build_infrastructure_type:
          title: Choose your Pipeline Infrastructure configuration
          type: string
          default: build_farm
          enum:
            - build_farm
            - custom
          enumNames:
            - Central Build Farm Infrastructure Only
            - Self-Hosted Kubernetes Infrastructure
        infra_defaults:
          title: infra_defaults
          type: object
          ui:widget: hidden
          properties:
            kubernetes_connector:
              type: string
              default: account.buildfarm_infrastructure
            kubernetes_namespace:
              type: string
              default: default
            kubernetes_override_image_connector:
              type: string
              default: ""
            kubernetes_node_selectors:
              type: string
              default: ""
      dependencies:
        build_infrastructure_type:
          allOf:
            - if:
                properties:
                  build_infrastructure_type:
                    const: "custom"
              then:
                required:
                  - kubernetes_connector
                  - kubernetes_namespace
                properties:
                  kubernetes_connector:
                    title: Existing Kubernetes Infrastructure Connector Reference
                    type: string
                    description: Enter the existing Kubernetes connector if local K8s execution should be used when running the Execution pipeline.  Must exist before execution.
                  kubernetes_namespace:
                    title: Existing Kubernetes Infrastructure Namespace
                    type: string
                    description: Enter the existing Kubernetes namespace if local K8s execution should be used when running the Execution pipeline.  Must exist before execution
                  kubernetes_override_image_connector:
                    title: Existing Override Image Container Connector Reference
                    type: string
                    description: Enter an existing Container Registry connector to use which overrides the default connector.  Must exist before execution
                  kubernetes_node_selectors:
                    title: Map of Kubernetes Node Selectors (Must be in key:value JSON)
                    type: object
                    description: Optional Kubernetes Node Selectors
                    additionalProperties:
                      type: string
    - title: Solutions Factory Connection
      properties:
        solutions_factory_details:
          title: Solutions Factory Details
          type: object
          description: |
            ---
            Harness URL : <+variable.account.solutions_factory_endpoint>

            Harness Account : <+account.identifier>

            Solutions Factory Org : <+variable.account.solutions_factory_org>

            Solutions Factory Project : <+variable.account.solutions_factory_project>
          required:
            - harness_account_url
            - harness_account_id
            - harness_org_id
            - harness_project_id
            - template_library_connector
            - template_library_repo
            - template_library_branch
            - template_library_directory
          properties:
            harness_account_url:
              type: string
              default: <+variable.account.solutions_factory_endpoint>
              ui:widget: hidden
            harness_account_id:
              type: string
              default: <+account.identifier>
              ui:widget: hidden
            harness_org_id:
              type: string
              default: <+variable.account.solutions_factory_org>
              ui:widget: hidden
            harness_project_id:
              type: string
              default: <+variable.account.solutions_factory_project>
              ui:widget: hidden
            template_library_connector:
              type: string
              default: <+variable.account.solutions_factory_template_library_connector>
              ui:widget: hidden
            template_library_repo:
              type: string
              default: <+variable.account.solutions_factory_template_library_repo>
              ui:widget: hidden
            template_library_branch:
              type: string
              default: main
              ui:widget: hidden
            template_library_directory:
              type: string
              default: ccm-autostop-primer
              ui:widget: hidden
        solutions_factory_opts:
          title: Solutions Factory Workflow Options
          type: object
          required:
            - repo_source
            - workspace_type
          properties:
            repo_source:
              type: string
              # Used to group by source the workspaces for bulk actions
              default: <+<+variable.account.solutions_factory_template_library_connector>.startsWith("org.Harness_Template_Library_Repo")?"official":"custom">
              ui:widget: hidden
            workspace_type:
              type: string
              # Used to group by type the workspaces for bulk actions
              default: ccm-autostop-primer
              ui:widget: hidden
            is_ephemeral:
              type: string
              # Determines if the workflow will trigger a temporary workspace that is
              # deleted upon completion. Resources will be preserved
              # Must be "true" or "false" and wrapped in quotes
              default: "false"
              ui:widget: hidden
            requires_approval:
              type: string
              # Determines if the workflow will require an Approval before executing
              # Must be "true" or "false" and wrapped in quotes
              default: "true"
              ui:widget: hidden
            use_mini_factory:
              type: string
              # "When enabled, IDP workflows will default to leveraging the mini-factory to distribute workloads
              # Value must be controlled through variable
              default: "false"
              ui:widget: hidden
  steps:
    - id: configure_workspace
      name: Configuring Harness Workspace
      action: trigger:harness-custom-pipeline
      input:
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ "hws_" if parameters.solutions_factory_opts.use_mini_factory=="true" else "" }}${{ parameters.organization_id if parameters.solutions_factory_opts.use_mini_factory=="true" else parameters.solutions_factory_details.harness_project_id }}/pipelines/Create_and_Manage_IACM_Workspaces/pipeline-studio?storeType=INLINE
        inputset:
          GIT_REPOSITORY_CONNECTOR: ${{ parameters.solutions_factory_details.template_library_connector }}
          GIT_REPOSITORY_NAME: ${{ parameters.solutions_factory_details.template_library_repo }}
          GIT_REPOSITORY_BRANCH: ${{ parameters.solutions_factory_details.template_library_branch }}
          GIT_REPOSITORY_PATH: ${{ parameters.solutions_factory_details.template_library_directory }}
          RESOURCE_NAME: ${{ parameters.template_name|replace(" ","_") }}
          RESOURCE_OWNER: group:default/harness_account_all_users
          # YAML of Terraform variables of type 'String' mapped to their IDP parameters
          RESOURCE_VARS:
            harness_platform_account: ${{ parameters.solutions_factory_details.harness_account_id }}

            template_name: ${{ parameters.template_name }}
            template_version: ${{ parameters.template_version }}
            template_organization_id: ${{ parameters.org_id if parameters.project_id else ( parameters.org_id if parameters.org_id else "") }}
            template_project_id: ${{ parameters.project_id if parameters.project_id else "" }}

            pipeline_organization_id: ${{ parameters.solutions_factory_details.harness_org_id }}
            pipeline_project_id: ${{ parameters.solutions_factory_details.harness_project_id }}
            existing_harness_platform_key_ref: ${{ parameters.existing_harness_platform_key_ref }}
            docker_connector: ${{ parameters.docker_connector }}
            image: ${{ parameters.image }}

            kubernetes_connector: ${{ parameters.infra_defaults.kubernetes_connector if (parameters.build_infrastructure_type == "build_farm") else parameters.kubernetes_connector }}
            kubernetes_namespace: ${{ parameters.infra_defaults.kubernetes_namespace if (parameters.build_infrastructure_type == "build_farm") else parameters.kubernetes_namespace }}
            kubernetes_node_selectors: ${{ parameters.kubernetes_node_selectors if parameters.kubernetes_node_selectors else parameters.infra_defaults.kubernetes_node_selectors }}
            kubernetes_override_image_connector: ${{ parameters.kubernetes_override_image_connector if parameters.kubernetes_override_image_connector else parameters.infra_defaults.kubernetes_override_image_connector }}
          # YAML of Terraform variables of type 'Secret' Reference mapped to their IDP parameters
          RESOURCE_VARS_SECRETS: {}
          # YAML of Environment variables of type 'String' mapped to their IDP parameters
          RESOURCE_VARS_ENVS: {}
          # YAML of Environment variables of type 'Secret' Reference mapped to their IDP parameters
          RESOURCE_VARS_ENVS_SECRET: {}
          # Should the workspace automatically include the default Harness Connector environment variables
          INCLUDE_HARNESS_ENVS: "true"
          WORKSPACE_TAGS:
            source: ${{ parameters.solutions_factory_opts.repo_source }}
            type: ${{ parameters.solutions_factory_opts.workspace_type }}
          IS_EPHEMERAL: ${{ parameters.solutions_factory_opts.is_ephemeral }}
          REQUIRES_APPROVAL: ${{ parameters.solutions_factory_opts.requires_approval }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
    - id: register_catalogs
      name: Register Catalog Creation Workflows
      action: trigger:harness-custom-pipeline
      input:
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ parameters.solutions_factory_details.harness_project_id }}/pipelines/Register_IDP_Templates/pipeline-studio?storeType=INLINE
        inputset:
          switch: children
          filter_template: ccm-autostop-primer
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Harness Workspace Configured - Execution Link
        url: ${{ steps.configure_workspace.output.PipelineUrl }}
    text:
      - title: Outputs
        content: |
          Step Template: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all${{ ("/orgs/" + parameters.org_id) if parameters.org_id else "" }}${{ ("/projects/" + parameters.project_id) if parameters.project_id else "" }}/settings/templates/${{ parameters.template_name|replace(" ","_")|replace("-","_") }}/template-studio/Step/?versionLabel=${{ parameters.template_version }}

          Service Modifier Pipeline: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ parameters.solutions_factory_details.harness_project_id }}/pipelines/add_autostopping_variables/pipeline-studio?storeType=INLINE
