apiVersion: harness.io/v1
kind: Workflow
identifier: ccmclusterorchestratordeployment
name: CCM Cluster Orchestrator Deployment
owner: group:default/harness_account_all_users # Defaults to all users
type: service
metadata:
  description: Create a Harness CD service for deploying the CCM cluster orchestrator
  tags:
    - solutions-factory
    - harness
    - ccm
    - cluster-orchestrator
    - cd
    - service
spec:
  parameters:
    - title: Service Setup
      required:
        - service_name
        - docker_connector
        - image
      properties:
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        service_name:
          title: Step Service Name
          type: string
          description: What should the "Commitment Orchestrator" step service be named
          default: Commitment Orchestrator
        docker_connector:
          title: Docker Connector
          type: string
          description: Docker connector ID for pulling controller image
          default: account.harnessImage
        image:
          title: Ansible image
          type: string
          default: harness/cluster-orchestrator
          description: Docker image to use for running the controller. Must follow repo/image format
        service_location:
          title: Service Location
          type: string
          description: Where should we place the service?
          enum:
            - Account
            - Organization
            - Project
      dependencies:
        service_location:
          oneOf:
          - properties:
              service_location:
                enum:
                  - Account
          - properties:
              service_location:
                enum:
                  - Organization
              org_id:
                title: Org Identifier
                description: Harness Organization Identifier
                type: string
                ui:field: HarnessOrgPicker
            required:
              - org_id
          - properties:
              service_location:
                enum:
                  - Project
              org_id:
                title: Org Identifier
                description: Harness Organization Identifier
                type: string
                ui:field: HarnessOrgPicker
              project_id:
                title: Project Identifier
                description: Harness Project Identifier
                type: string
                ui:field: HarnessProjectPicker
            required:
              - project_id
              - org_id
    - title: Solutions Factory Connection
      properties:
        solutions_factory_details:
          title: Solutions Factory Details
          type: object
          description: |
            ---
            Harness URL : <+variable.account.solutions_factory_endpoint>

            Harness Account : <+account.identifier>

            Solutions Factory Org : <+variable.account.solutions_factory_org>

            Solutions Factory Project : <+variable.account.solutions_factory_project>
          required:
            - harness_account_url
            - harness_account_id
            - harness_org_id
            - harness_project_id
            - template_library_connector
            - template_library_repo
            - template_library_branch
            - template_library_directory
          properties:
            harness_account_url:
              type: string
              default: <+variable.account.solutions_factory_endpoint>
              ui:widget: hidden
            harness_account_id:
              type: string
              default: <+account.identifier>
              ui:widget: hidden
            harness_org_id:
              type: string
              default: <+variable.account.solutions_factory_org>
              ui:widget: hidden
            harness_project_id:
              type: string
              default: <+variable.account.solutions_factory_project>
              ui:widget: hidden
            template_library_connector:
              type: string
              default: <+variable.account.solutions_factory_template_library_connector>
              ui:widget: hidden
            template_library_repo:
              type: string
              default: <+variable.account.solutions_factory_template_library_repo>
              ui:widget: hidden
            template_library_branch:
              type: string
              default: main
              ui:widget: hidden
            template_library_directory:
              type: string
              default: ccm-cluster-orchestrator-deployment
              ui:widget: hidden
        solutions_factory_opts:
          title: Solutions Factory Workflow Options
          type: object
          required:
            - repo_source
            - workspace_type
          properties:
            repo_source:
              type: string
              # Used to group by source the workspaces for bulk actions
              default: <+<+variable.account.solutions_factory_template_library_connector>.startsWith("org.Harness_Template_Library_Repo")?"official":"custom">
              ui:widget: hidden
            workspace_type:
              type: string
              # Used to group by type the workspaces for bulk actions
              default: ccm-cluster-orchestrator-deployment
              ui:widget: hidden
            is_ephemeral:
              type: string
              # Determines if the workflow will trigger a temporary workspace that is
              # deleted upon completion. Resources will be preserved
              # Must be "true" or "false" and wrapped in quotes
              default: "false"
              ui:widget: hidden
            requires_approval:
              type: string
              # Determines if the workflow will require an Approval before executing
              # Must be "true" or "false" and wrapped in quotes
              default: "true"
              ui:widget: hidden
            use_mini_factory:
              type: string
              # "When enabled, IDP workflows will default to leveraging the mini-factory to distribute workloads
              # Value must be controlled through variable
              default: "false"
              ui:widget: hidden
  steps:
    - id: configure_workspace
      name: Configuring Harness Workspace
      action: trigger:harness-custom-pipeline
      input:
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ "hws_" if parameters.solutions_factory_opts.use_mini_factory=="true" else "" }}${{ parameters.organization_id if parameters.solutions_factory_opts.use_mini_factory=="true" else parameters.solutions_factory_details.harness_project_id }}/pipelines/Create_and_Manage_IACM_Workspaces/pipeline-studio?storeType=INLINE
        inputset:
          GIT_REPOSITORY_CONNECTOR: ${{ parameters.solutions_factory_details.template_library_connector }}
          GIT_REPOSITORY_NAME: ${{ parameters.solutions_factory_details.template_library_repo }}
          GIT_REPOSITORY_BRANCH: ${{ parameters.solutions_factory_details.template_library_branch }}
          GIT_REPOSITORY_PATH: ${{ parameters.solutions_factory_details.template_library_directory }}
          RESOURCE_NAME: ${{ parameters.org_id if parameters.project_id else ( parameters.org_id if parameters.org_id else "") }}_${{ parameters.project_id if parameters.project_id else "" }}_ccm_cluster_orchestrator
          RESOURCE_OWNER: group:default/harness_account_all_users
          # YAML of Terraform variables of type 'String' mapped to their IDP parameters
          RESOURCE_VARS:
            service_name: ${{ parameters.service_name }}
            organization_id: ${{ parameters.org_id if parameters.project_id else ( parameters.org_id if parameters.org_id else "") }}
            project_id: ${{ parameters.project_id if parameters.project_id else "" }}

            docker_connector: ${{ parameters.docker_connector }}
            image: ${{ parameters.image }}
          # YAML of Terraform variables of type 'Secret' Reference mapped to their IDP parameters
          RESOURCE_VARS_SECRETS: {}
          # YAML of Environment variables of type 'String' mapped to their IDP parameters
          RESOURCE_VARS_ENVS: {}
          # YAML of Environment variables of type 'Secret' Reference mapped to their IDP parameters
          RESOURCE_VARS_ENVS_SECRET: {}
          # Should the workspace automatically include the default Harness Connector environment variables
          INCLUDE_HARNESS_ENVS: "true"
          WORKSPACE_TAGS:
            source: ${{ parameters.solutions_factory_opts.repo_source }}
            type: ${{ parameters.solutions_factory_opts.workspace_type }}
          IS_EPHEMERAL: ${{ parameters.solutions_factory_opts.is_ephemeral }}
          REQUIRES_APPROVAL: ${{ parameters.solutions_factory_opts.requires_approval }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Harness Workspace Configured - Execution Link
        url: ${{ steps.configure_workspace.output.PipelineUrl }}
      - title: View Service
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all${{ ("/orgs/" + parameters.org_id) if parameters.org_id else "" }}${{ ("/projects/" + parameters.project_id) if parameters.project_id else "" }}/settings/services/${{ parameters.service_name|replace(" ","_")|replace("-","_") }}
