pipeline:
  identifier: ${PIPELINE_IDENTIFIER}
  name: ${PIPELINE_NAME}
  orgIdentifier: ${ORGANIZATION_ID}
  projectIdentifier: ${PROJECT_ID}
  description: "${DESCRIPTION}"
  tags:
    ${indent(4, TAGS)}
  properties:
    ci:
      codebase:
        %{~ if REPOSITORY_CONNECTOR != null }
        connectorRef: ${REPOSITORY_CONNECTOR}
        %{~ endif ~}
        repoName: ${REPOSITORY_PATH}
        build: <+input>
  stages:
    - stage:
        name: Repository Scans
        identifier: Repository_Scans
        template:
          templateRef: ${TEMPLATE_ID}
          versionLabel: ${TEMPLATE_VERSION}
          templateInputs:
            type: SecurityTests
            variables:
              - name: SCAN_TARGET
                type: String
                value: <+pipeline.properties.ci.codebase.repoName>
              - name: SCAN_VARIANT
                type: String
                value: <+codebase.branch>
              - name: SHARED_ARTIFACTS
                type: String
                value: /shared/customer_artifacts
              - name: GITLEAKS_CPU
                type: String
                value: 400m
              - name: GITLEAKS_MEM
                type: String
                value: 600Mi
              - name: OSV_CPU
                type: String
                value: "1"
              - name: OSV_MEM
                type: String
                value: 2Gi
              - name: OWASP_CPU
                type: String
                value: "2"
              - name: OWASP_MEM
                type: String
                value: 6Gi
              - name: SEMGREP_CPU
                type: String
                value: "2"
              - name: SEMGREP_MEM
                type: String
                value: 4Gi
