apiVersion: harness.io/v1
kind: Workflow
name: Create Repository and Pipeline
identifier: ci_sto_hcr_standard
type: harness_factory
owner: group:account/HSF_Admins
metadata:
  description: |
    Creates a new Harness Code Repository and CI pipeline with SAST and SCA scans
  annotations:
    is_harness_official: "True"
    source: harness-template-library
    created_by: Harness
  tags:
    - solutions-factory
    - harness
    - ci
    - pipeline
spec:
  parameters:
    - title: Pipeline Configuration
      description: |
        ---
        Create a new CI pipeline using the Golden Standard templates that have been deployed.

        This workflow will create:
        - A new Harness Code Repository with Security Rules
        - A new CI pipeline using the Golden Standard template with SAST and SCA scans
        - Pre-configured Harness triggers with input sets for each trigger
        - Ready to run with the standardized CI workflow

        ---

        _Note: This requires that both the STO SAST/SCA Primer and CI Golden Standards templates have already been deployed._
      properties:
        project_id:
          title: Select the Harness Project into which the pipeline will be deployed
          type: string
          description: Harness Project where the pipeline will be created
          ui:field: HarnessProjectPicker
        organization_id:
          title: Organization ID
          type: string
          description: Harness Organization where the pipeline will be created
          ui:widget: hidden
          ui:field: HarnessAutoOrgPicker
          dependencies:
            projectPickerRef:
              - 'project_id'
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
    - title: Repository Registration
      properties:
        repository_name:
          title: What is the name of the repository?
          description: A new pipeline will be created based on this name
          type: string
          pattern: '^[a-zA-Z_][a-zA-Z0-9-_.]{0,127}$'
        repository_description:
          title: Provide the Description for the Repository
          type: string
        repository_rule_is_active:
          title: Set the Trigger State
          description: When 'active' will enforce repository rules preventing changes except by CODEOWNERS
          type: string
          default: active
          enum:
            - active
            - disabled
            - monitor
        repository_merge_strategies:
          title: Choose the Pull-Request Merge Strategy
          description: Limit which merge strategies are available to merge a pull request
          type: array
          default:
            - squash
          items:
            type: string
            enum:
              - fast-forward
              - merge
              - rebase
              - squash
    - title: Solutions Factory Connection
      properties:
        solutions_factory_details:
          title: Solutions Factory Details
          type: object
          description: |
            ---
            Harness URL : <+variable.account.solutions_factory_endpoint>

            Harness Account : <+account.identifier>

            Solutions Factory Org : <+variable.account.solutions_factory_org>

            Solutions Factory Project : <+variable.account.solutions_factory_project>
          required:
            - harness_account_url
            - harness_account_id
            - harness_org_id
            - harness_project_id
            - template_library_connector
            - template_library_repo
            - template_library_branch
            - template_library_directory
          properties:
            harness_account_url:
              type: string
              default: <+variable.account.solutions_factory_endpoint>
              ui:widget: hidden
            harness_account_id:
              type: string
              default: <+account.identifier>
              ui:widget: hidden
            harness_org_id:
              type: string
              default: <+variable.account.solutions_factory_org>
              ui:widget: hidden
            harness_project_id:
              type: string
              default: <+variable.account.solutions_factory_project>
              ui:widget: hidden
            buildfarm_connector:
              type: string
              default: <+variable.account.CI_Default_Build_Farm_SCM_Connector>
              ui:widget: hidden
            template_library_connector:
              type: string
              default: <+variable.account.solutions_factory_template_library_connector>
              ui:widget: hidden
            template_library_repo:
              type: string
              default: <+variable.account.solutions_factory_template_library_repo>
              ui:widget: hidden
            template_library_branch:
              type: string
              default: main
              ui:widget: hidden
            template_library_directory:
              type: string
              default: ci-sto-hcr-standard
              ui:widget: hidden
        solutions_factory_opts:
          title: Solutions Factory Workflow Options
          type: object
          required:
            - repo_source
            - workspace_type
          properties:
            repo_source:
              type: string
              # Used to group by source the workspaces for bulk actions
              default: <+<+variable.account.solutions_factory_template_library_connector>.startsWith("org.Harness_Template_Library_Repo")?"official":"custom">
              ui:widget: hidden
            workspace_type:
              type: string
              # Used to group by type the workspaces for bulk actions
              default: ci-sto-hcr-standard
              ui:widget: hidden
            is_ephemeral:
              type: string
              # Determines if the workflow will trigger a temporary workspace that is
              # deleted upon completion. Resources will be preserved
              # Must be "true" or "false" and wrapped in quotes
              default: "true"
              ui:widget: hidden
            requires_approval:
              type: string
              # Determines if the workflow will require an Approval before executing
              # Must be "true" or "false" and wrapped in quotes
              default: "false"
              ui:widget: hidden
            use_mini_factory:
              type: string
              # "When enabled, IDP workflows will default to leveraging the mini-factory to distribute workloads
              # Value must be controlled through variable
              default: <+variable.account.enable_hsf_mini_factory>
              ui:widget: hidden
  steps:
    - id: configure_workspace
      name: Configuring Harness Workspace
      action: trigger:harness-custom-pipeline
      input:
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ "hws_" if parameters.solutions_factory_opts.use_mini_factory=="true" else "" }}${{ parameters.organization_id if parameters.solutions_factory_opts.use_mini_factory=="true" else parameters.solutions_factory_details.harness_project_id }}/pipelines/Create_and_Manage_IACM_Workspaces/pipeline-studio?storeType=INLINE
        inputset:
          GIT_REPOSITORY_CONNECTOR: ${{ parameters.solutions_factory_details.template_library_connector }}
          GIT_REPOSITORY_NAME: ${{ parameters.solutions_factory_details.template_library_repo }}
          GIT_REPOSITORY_BRANCH: ${{ parameters.solutions_factory_details.template_library_branch }}
          GIT_REPOSITORY_PATH: ${{ parameters.solutions_factory_details.template_library_directory }}
          RESOURCE_NAME: CISTOHCR_${{ parameters.organization_id }}_${{ parameters.project_id }}_${{ parameters.repository_name|replace(" ","-")|replace("-", "_") }}
          RESOURCE_OWNER: group:default/HSF_Admins
          # YAML of Terraform variables mapped to IDP parameters
          RESOURCE_VARS:
            organization_id: ${{ parameters.organization_id }}
            project_id: ${{ parameters.project_id }}
            repository_name: ${{ parameters.repository_name }}
            repository_description: ${{ parameters.repository_description }}
            repository_rule_is_active: ${{ parameters.repository_rule_is_active }}
            repository_merge_strategies: ${{ parameters.repository_merge_strategies }}
          RESOURCE_VARS_SECRETS: {}
          RESOURCE_VARS_ENVS: {}
          RESOURCE_VARS_ENVS_SECRET: {}
          INCLUDE_HARNESS_ENVS: "true"
          WORKSPACE_TAGS:
            source: ${{ parameters.solutions_factory_opts.repo_source }}
            type: ${{ parameters.solutions_factory_opts.workspace_type }}
            organization: ${{ parameters.organization_id }}
            project: ${{ parameters.project_id }}
            pipeline: ${{ parameters.pipeline_name }}
          IS_EPHEMERAL: ${{ parameters.solutions_factory_opts.is_ephemeral }}
          REQUIRES_APPROVAL: ${{ parameters.solutions_factory_opts.requires_approval }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Next - Update the Pipeline Input Set
        url: ${{ steps.configure_workspace.output['pipeline.stages.Provision.spec.execution.steps.Provision.steps.apply.output.outputVariables.pipeline_input_set']}}
    text:
      - title: Pipeline Created Successfully
        content: |
          🎉 **Pipeline Created Successfully!**

          Your new CI pipeline has been created using the Golden Standard templates.

          **Pipeline Details:**
          - **Name**: ${{ parameters.repository_name }}
          - **Organization**: ${{ parameters.organization_id }}
          - **Project**: ${{ parameters.project_id }}
          - **Repository**: ${{ parameters.repository_name }}

          **What's Included:**
          - ✅ Code smells and linting checks (If enabled by platform team)
          - ✅ Container image build and security scanning
          - ✅ Supply chain security validation (If enabled by platform team)
          - ✅ Integration with your Git repository

          **Next Steps:**
          1. Modify the Pipeline Input Set by clicking on the link above
          2. Configure any repository-specific settings
          3. Set up or enable triggers as needed
          3. Run your first pipeline execution

          Your pipeline is ready to use with all the Golden Standard CI best practices!
